language: python
python:
- '3.6'
script:
- pytest
deploy:
  provider: pypi
  user: DobbleG1000
  password:
    secure: csFO2UowhtaX3d2+kOISrz690dtvPv9Jj3dFuhT+i5Yh+cAoKshS2RWOT5WjURdB+3kR+EcsiHh6o85AjxOssn0fb6d6wF48luHIcsbW3k3wH6PTcTlUYdGxjdHIxxwYIV5+S2QyYgRYLBIu/weyWbyYboFjMD5ZqZC4O/15TyXmqHHAx1Ba3M+CyUOPsQPm7hdU/CgtFJzxgir9wy+DWVWbgMrb2c9U92996nvXnZBrwYSy6/3fC0O7+egHrFJ9iikXacjpIa1Sz6Dia5rQfQ4UKFARYm5LcT7hY8zeKYAQ4D72V0ShIvdkKx+y1sL25ROAF6rkFmhO2TEBGIlOi1ZgJP12wmBCbat84+1IgtM/x3DugnGPsjJdd2hZn2GLbdVan+sUVpQLLcIQcQDsFXmV/7Z3KA/ILm+y3gQ9In9tKWme78HJN6Ayd+0JIbJ0wipdaM5GXBaF7BKFbebISAeBMsCrasqkbOjONIeiYToXW6GcaeUZ8u7KyBePohI7lVPkBoIpRZO8qacFux8LBNEytGS5U0QMHVP5N7qfLdU68phK0XHeUcNgNLxTw+u2an7W7eDI/f7OaXBAEyfvg3j943WwPksKGm2rLRwojhI75KE3VYcE4cc94rOtNvNMDtW9t7Wvn4M91jbJpjx642rLPev2RKhinEZyQErpogc=
  on:
    tags: true
